--Criação das Tabelas
CREATE TABLE DADOS_BANCARIO (
	COD_DADOS_BANCARIO INT NOT NULL,
	BANCO              VARCHAR(50),
	AGENCIA            VARCHAR(50),
	CONTA			   VARCHAR(15),
	CONSTRAINT PK_DADOS_BANCARIO
		PRIMARY KEY (COD_DADOS_BANCARIO)
);

CREATE TABLE POSTO (
	CNPJ INT NOT NULL,
	COD_DADOS_BANCARIO  INT NOT NULL,
	NOME_FANTASIA       VARCHAR(50),
	RAZAO_SOCIAL        VARCHAR(50),
	TELEFONE            VARCHAR(14),
	CONSTRAINT PK_POSTO
		PRIMARY KEY (CNPJ)
);

CREATE TABLE CLIENTE (
	COD_CLIENTE         INT NOT NULL,
	COD_DADOS_BANCARIO  INT NOT NULL,
	ENDERECO            VARCHAR(50),
	TELEFONE            VARCHAR(14),
	CONSTRAINT PK_CLIENTE
		PRIMARY KEY (COD_CLIENTE)
);

CREATE TABLE HISTORICO_ABASTECIMENTO (
	CNPJ_POSTO               INT NOT NULL,
	COD_CLIENTE        INT NOT NULL,
	VALOR              INT NOT NULL,
	NUM_DOCUMENTO	   INT NOT NULL,
	COD_TIPO_CLIENTE   INT NOT NULL,
	CONSTRAINT PK_HISTORICO_ABASTECIMENTO
		PRIMARY KEY (CNPJ_POSTO, COD_CLIENTE)
);

CREATE TABLE DEPENDENTE (
	CNH               INT NOT NULL,
	COD_CLIENTE       INT NOT NULL,
	NOME              VARCHAR(50),
	CONSTRAINT PK_DEPENDENTE
		PRIMARY KEY (CNH)
);

CREATE TABLE CLIENTE_PJ (
	CNPJ              INT NOT NULL,
	COD_CLIENTE       INT NOT NULL,
	NOME_FANTASIA     VARCHAR(50),
	RAZAO_SOCIAL      VARCHAR(50),
	CONSTRAINT PK_CLIENTE_PJ
		PRIMARY KEY (CNPJ)
);

CREATE TABLE CLIENTE_PF (
	CPF               INT NOT NULL,
	COD_CLIENTE       INT NOT NULL,
	NOME              VARCHAR(50),
	NUM_CNH           INT,
	CONSTRAINT PK_CLIENTE_PF
		PRIMARY KEY (CPF)
);

CREATE TABLE TIPO_CLIENTE (
	CODIGO            INT NOT NULL,
	DESCRICAO	      VARCHAR(50) NULL,
	CONSTRAINT PK_TIPO_CLIENTE
		PRIMARY KEY (CODIGO)
);

--Crição das chaves extrangeiras
ALTER TABLE CLIENTE_PF ADD CONSTRAINT FK_CLIENTE_PF_CLIENTE
	FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE);

ALTER TABLE CLIENTE_PJ ADD CONSTRAINT FK_CLIENTE_PJ_CLIENTE
	FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE);

ALTER TABLE DEPENDENTE ADD CONSTRAINT FK_DEPENDENTE_CLIENTE
	FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE);

ALTER TABLE HISTORICO_ABASTECIMENTO ADD CONSTRAINT FK_HISTORICO_POSTO
	FOREIGN KEY (CNPJ_POSTO) REFERENCES POSTO (CNPJ);

ALTER TABLE HISTORICO_ABASTECIMENTO ADD CONSTRAINT FK_HISTORICO_CLIENTE
	FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE);

ALTER TABLE HISTORICO_ABASTECIMENTO ADD CONSTRAINT FK_HISTORICO_TIPO_CLIENTE
	FOREIGN KEY (COD_TIPO_CLIENTE) REFERENCES TIPO_CLIENTE (CODIGO);


ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_DADOS_BANCARIO
	FOREIGN KEY (COD_DADOS_BANCARIO) REFERENCES DADOS_BANCARIO (COD_DADOS_BANCARIO);

ALTER TABLE POSTO ADD CONSTRAINT FK_POSTO_DADOS_BANCARIO
	FOREIGN KEY (COD_DADOS_BANCARIO) REFERENCES DADOS_BANCARIO (COD_DADOS_BANCARIO);

--Criação das seguences
CREATE SEQUENCE DADOS_BANCARIO_SEQ;

CREATE SEQUENCE CLIENTE_SEQ;

--Carga dos dados
INSERT INTO TIPO_CLIENTE (CODIGO, DESCRICAO) VALUES (1, 'CLIENTE_PF');
INSERT INTO TIPO_CLIENTE (CODIGO, DESCRICAO) VALUES (2, 'CLIENTE_PJ');
INSERT INTO TIPO_CLIENTE (CODIGO, DESCRICAO) VALUES (3, 'DEPENDENTE'); 

