----------------------------------------------
-- Script de criação das tabelas do banco de dados de 
-- agenda online
--
-- Versão: 1
-- Data: 05/02/2011
-- Autor: Nayalison
--
-----------------------------------------------

-----------------------------------------------
--Criação das tabelas
-----------------------------------------------

--Tabela de grupo de contatos
CREATE TABLE GRUPO (
	COD_GRUPO BIGINT NOT NULL,
	NOME_GRUPO VARCHAR(50) NOT NULL,
	DESCRICAO VARCHAR(200)
);

--Tabela de anotações
CREATE TABLE ANOTACAO (
	COD_ANOTACAO BIGINT NOT NULL,
	TITULO VARCHAR(80) NOT NULL,
	CONTEUDO TEXT,
	COD_USUARIO BIGINT NOT NULL
);

--Tabela de meios de contato
CREATE TABLE MEIO_CONTATO (
	COD_MEIO_CONTATO BIGINT NOT NULL,
	TIPO_MEIO_CONTATO VARCHAR(8) NOT NULL,
	VALOR VARCHAR(100) NOT NULL,
	COD_CONTATO BIGINT NOT NULL
);

--Tabela de endereços
CREATE TABLE ENDERECO (
	COD_ENDERECO BIGINT NOT NULL,
	NUMERO BIGINT NOT NULL,
	CEP VARCHAR(8) NOT NULL,
	LOGRADOURO VARCHAR(80) NOT NULL,
	COMPLEMENTO VARCHAR(50) NOT NULL,
	BAIRRO VARCHAR(80) NOT NULL,
	CIDADE VARCHAR(80) NOT NULL,
	UF VARCHAR(2) NOT NULL
);

--Tabela de compromiços
CREATE TABLE COMPROMICO (
	COD_COMPROMICO BIGINT NOT NULL,
	DATA_COMPROMICO DATE ,
	HORA_INICIO TIME,
	HORA_TERMINO TIME,
	LOCAL_COMPROMICO VARCHAR(100) NOT NULL,
	COD_ENDERECO BIGINT ,
	DESCRICAO VARCHAR(200),
	CLASSIFICACAO VARCHAR(17) NOT NULL,
	COD_USUARIO BIGINT NOT NULL
);

--Tabela de contatos      
CREATE TABLE CONTATO(
	COD_CONTATO BIGINT NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	COD_GRUPO BIGINT NOT NULL,
	COD_ENDERECO BIGINT,
	COD_USUARIO BIGINT NOT NULL
);

--Tabela de usuários
CREATE TABLE USUARIO (
	COD_USUARIO BIGINT NOT NULL,
	PRIMEIRO_NOME VARCHAR(80) NOT NULL,
	SEGUNDO_NOME VARCHAR(80) NOT NULL,
	LOGIN VARCHAR(50) NOT NULL,
	SENHA VARCHAR(50) UNIQUE NOT NULL,
	COD_ENDERECO BIGINT
);


-----------------------------------------------
--Criação das chaves primárias
-----------------------------------------------

--Chave primária da tabela GRUPO
ALTER TABLE GRUPO ADD CONSTRAINT PK_GRUPO PRIMARY KEY(COD_GRUPO);

--Chave primária da tabela ANOTACAO
ALTER TABLE ANOTACAO ADD CONSTRAINT PK_ANOTACAO PRIMARY KEY(COD_ANOTACAO);

--Chave primária da tabela MEIO_CONTATO
ALTER TABLE MEIO_CONTATO ADD CONSTRAINT PK_MEIO_CONTATO PRIMARY KEY(COD_MEIO_CONTATO);

--Chave primária da tabela ENDERECO
ALTER TABLE ENDERECO ADD CONSTRAINT PK_ENDERECO PRIMARY KEY(COD_ENDERECO);

--Chave primária da tabela COMPROMICO
ALTER TABLE COMPROMICO ADD CONSTRAINT PK_COMPROMICO PRIMARY KEY(COD_COMPROMICO);

--Chave primária da tabela CONTATO
ALTER TABLE CONTATO ADD CONSTRAINT PK_CONTATO PRIMARY KEY(COD_CONTATO);

--Chave primária da tabela USUARIO
ALTER TABLE USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY(COD_USUARIO);


-----------------------------------------------
--Criação das chaves estrangeiras
-----------------------------------------------

--Chave estrangeira da tabela ANOTACAO
ALTER TABLE ANOTACAO ADD CONSTRAINT FK_USUARIO_ANOTACAO FOREIGN KEY (COD_USUARIO)
      REFERENCES USUARIO (COD_USUARIO) MATCH SIMPLE  ON UPDATE CASCADE ON DELETE CASCADE;
      
--Chave estrangeira da tabela MEIO_CONTATO
ALTER TABLE MEIO_CONTATO ADD CONSTRAINT FK_CONTATO_MEIO_CONTATO FOREIGN KEY (COD_CONTATO)
      REFERENCES CONTATO (COD_CONTATO) MATCH SIMPLE  ON UPDATE CASCADE ON DELETE CASCADE;

--Chaves estrangeiras da tabela COMPROMICO
ALTER TABLE COMPROMICO ADD CONSTRAINT FK_ENDERECO_COMPROMICO FOREIGN KEY (COD_ENDERECO)
      REFERENCES ENDERECO (COD_ENDERECO) MATCH SIMPLE  ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE COMPROMICO ADD CONSTRAINT FK_USUARIO_COMPROMICO FOREIGN KEY (COD_USUARIO)
      REFERENCES USUARIO (COD_USUARIO) MATCH SIMPLE  ON UPDATE CASCADE ON DELETE CASCADE;
            
--Chaves estrangeiras da tabela CONTATO
ALTER TABLE CONTATO ADD CONSTRAINT FK_ENDERECO_CONTATO FOREIGN KEY (COD_ENDERECO)
      REFERENCES ENDERECO (COD_ENDERECO) MATCH SIMPLE  ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE CONTATO ADD CONSTRAINT FK_USUARIO_CONTATO FOREIGN KEY (COD_USUARIO)
      REFERENCES USUARIO (COD_USUARIO) MATCH SIMPLE  ON UPDATE CASCADE ON DELETE CASCADE;
      
--Chave estrangeira da tabela USUARIO
ALTER TABLE USUARIO ADD CONSTRAINT FK_ENDERECO_USUARIO FOREIGN KEY (COD_ENDERECO)
      REFERENCES ENDERECO (COD_ENDERECO) MATCH SIMPLE  ON UPDATE CASCADE ON DELETE CASCADE;
      
      
-----------------------------------------------
--Criação das seguences
-----------------------------------------------

--Seguence da tabela GRUPO   
CREATE SEQUENCE GRUPO_SEQ
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1;

--Seguence da tabela ANOTACAO   
CREATE SEQUENCE ANOTACAO_SEQ
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1;
    
--Seguence da tabela MEIO_CONTATO   
CREATE SEQUENCE MEIO_CONTATO_SEQ
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1;

--Seguence da tabela ENDERECO   
CREATE SEQUENCE ENDERECO_SEQ
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1;
    
--Seguence da tabela COMPROMICO   
CREATE SEQUENCE COMPROMICO_SEQ
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1;
    
--Seguence da tabela CONTATO   
CREATE SEQUENCE CONTATO_SEQ
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1;
    
--Seguence da tabela USUARIO   
CREATE SEQUENCE USUARIO_SEQ
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1;
